# Generated by Django 5.1 on 2024-08-20 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aws", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EC2Instance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("instance_id", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("instance_type", models.CharField(max_length=20)),
                ("region", models.CharField(max_length=20)),
                ("availability_zone", models.CharField(max_length=20)),
                ("public_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("private_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("state", models.CharField(max_length=20)),
                ("launch_time", models.DateTimeField()),
                ("iam_role", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="IAMPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=255)),
                ("resource", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="IAMPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("policy_name", models.CharField(max_length=255, unique=True)),
                ("policy_id", models.CharField(max_length=128, unique=True)),
                ("arn", models.CharField(max_length=255)),
                ("create_date", models.DateTimeField()),
                ("policy_document", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="LambdaFunction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("function_name", models.CharField(max_length=255, unique=True)),
                ("function_arn", models.CharField(max_length=255, unique=True)),
                ("runtime", models.CharField(max_length=64)),
                ("handler", models.CharField(max_length=255)),
                ("role", models.CharField(max_length=255)),
                ("code_size", models.BigIntegerField()),
                ("description", models.TextField(blank=True, null=True)),
                ("timeout", models.IntegerField()),
                ("memory_size", models.IntegerField()),
                ("last_modified", models.DateTimeField()),
                ("region", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="S3Bucket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("region", models.CharField(max_length=20)),
                ("creation_date", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="SQSQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("queue_name", models.CharField(max_length=255, unique=True)),
                ("queue_url", models.URLField(max_length=1024, unique=True)),
                ("region", models.CharField(max_length=64)),
                ("arn", models.CharField(max_length=255, unique=True)),
                ("created_timestamp", models.DateTimeField()),
                ("visibility_timeout", models.IntegerField()),
                ("maximum_message_size", models.IntegerField()),
                ("message_retention_period", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="IAMRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role_name", models.CharField(max_length=255, unique=True)),
                ("role_id", models.CharField(max_length=128, unique=True)),
                ("arn", models.CharField(max_length=255)),
                ("create_date", models.DateTimeField()),
                (
                    "policies",
                    models.ManyToManyField(related_name="roles", to="aws.iampolicy"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IAMInlinePolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("policy_name", models.CharField(max_length=255)),
                ("policy_document", models.JSONField()),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inline_policies",
                        to="aws.iamrole",
                    ),
                ),
            ],
        ),
    ]
