---
- name: Set up Ubuntu
  hosts: all
  become: yes
  tasks:
    - name: Set hostname "{{ hostname }}"
      hostname:
        name: "{{ hostname }}"

    - name: Copy dotfiles to root
      get_url:
        url: "https://raw.githubusercontent.com/quxdev/qconfig/main/shell/{{ item }}"
        dest: "$HOME/.{{ item }}"
        force: yes
      with_items: "{{ dotfiles }}"

    - name: Update all packages
      apt:
        update_cache: yes

    - name: Install list of packages
      apt:
        pkg: "{{ ubuntu_packages }}"

    - name: Upgrade all packages
      apt:
        upgrade: dist

    - name: Apt autoclean
      apt:
        autoclean: yes

    - name: Apt autoremove
      apt:
        autoremove: yes

    - name: Add apt-get key from URL
      apt_key:
        url: https://dl.google.com/linux/linux_signing_key.pub
        state: present

    - name: Copy options-ssl-apache.conf to /etc/letsencrypt/
      copy:
        src: ../files/etc/letsencrypt/options-ssl-apache.conf
        dest: /etc/letsencrypt/

    - name: Enable WSGI
      apache2_module:
        state: present
        name: wsgi

    - name: Enable SSL
      apache2_module:
        state: present
        name: ssl